# Uncomment this line to define a global platform for your project
platform :ios, "8.0"

source 'https://github.com/CocoaPods/Specs.git'

target "YahooDemo" do

pod 'AFNetworking', '~> 2.6'
pod "youtube-ios-player-helper", "~> 0.1.4"
pod 'MBProgressHUD'

end

target "YahooDemoTests" do

end

target "YahooDemoUITests" do

end

